### PR TITLE
Added ubuntu support to grub timeout change.

### PR DESCRIPTION
**Pull request by nickryand**
Hey Pat, 

I started using this repository a couple of weeks ago and wanted to help out.

I am not 100 percent sure the timeout should live users.rb since it is platform specific. It seems like it should live in the desktop_rhel recipe and I should submit a pull request with a desktop_ubuntu recipe where my addition would live. What do you think?

### CODE REVIEW

**Comment by nickryand** [comment]
Fixed the spacing. Needed to remove the tabs.

**Comment by webcoyote** [comment]
Thanks Nick, I merged it. In regard to putting the grub bootloader changes somewhere, you're right that they don't belong in users.rb. They don't belong in desktop, either! If I have any more "non-desktop", "non-user" additions I'll pull out that change and add it to another file.

**Comment by nickryand** [comment]
Cool! Thanks for putting this up on Github and for responding so fast.

**Comment by webcoyote** [comment]
Nick,

You get special bonus points and a fast response because you submitted my
first unsolicited pull request on Github. Incidentally, say hi to Mark @ R5
for me, would ya? I haven't seen him in about 12 years!

Thanks again,

Pat

**Pull request merged**
